import { ParsedExpense, SocialContext, LocationType } from '../modules/registration/types';
import uuid from 'react-native-uuid';

export const DUMMY_TRANSACTIONS: Partial<ParsedExpense>[] = [
  { amount: 9.0, description: "Braccialetto badge palestra nuovo", category_key: "vita_intrattenimento", subcategory_key: "sport_fitness", direction: "out", date: "2026-01-03", time: "18:30", location_type: "work", city: "Monza" },
  { amount: 1.5, description: "Supermercato mela", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-01-05", time: "12:45", location_type: "physical_store", city: "Vimercate" },
  { amount: 22.5, description: "Sushi - Ristorante giapponese", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-01-06", time: "20:30", social_context: "friends", city: "Monza" },
  { amount: 3.5, description: "McDonald's - McFlurry", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-01-06", time: "22:00", social_context: "friends", city: "Monza" },
  { amount: 8.8, description: "Biglietti treno lavoro", category_key: "trasporti", subcategory_key: "trasporto_pubblico", direction: "out", date: "2026-01-07", time: "08:15", city: "Milano" },
  { amount: 2.5, description: "Zuppa di cereali", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-01-07", time: "13:20", social_context: "colleagues", city: "Bernareggio" },
  { amount: 1.4, description: "MD - Spesa", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-01-08", time: "12:50", city: "Bernareggio" },
  { amount: 13.58, description: "SPLICE.COM - Abbonamento piattaforma musicale", category_key: "vita_intrattenimento", subcategory_key: "hobby", direction: "out", date: "2026-01-08", time: "10:00", location_type: "online" },
  { amount: 500.0, description: "Stipendio/pensione", category_key: "entrata", subcategory_key: "salario_fatture", direction: "in", date: "2026-01-12", time: "09:00" },
  { amount: 1.2, description: "MIAMI - Transazione con carta", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-01-12", time: "12:30", city: "Bernareggio" },
  { amount: 6.8, description: "FNM - Treno", category_key: "trasporti", subcategory_key: "trasporto_pubblico", direction: "out", date: "2026-01-13", time: "07:45", city: "Sesto San Giovanni" },
  { amount: 1.2, description: "MIAMI - Transazione non specificata", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-01-13", time: "10:30", city: "Bernareggio" },
  { amount: 1.2, description: "Caffè bar Vimercate - consumazione", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-01-14", time: "08:30", city: "Vimercate" },
  { amount: 1.2, description: "Caffè pausa pranzo", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-01-15", time: "13:45", city: "Milano", social_context: "colleagues" },
  { amount: 5.0, description: "MD BERNAR - Spesa al supermercato", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-01-16", time: "12:55", city: "Bernareggio" },
  { amount: 9.5, description: "Kebab pausa pranzo", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-01-16", time: "13:15", city: "Bernareggio", social_context: "colleagues" },
  { amount: 23.77, description: "American graffiti", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-01-17", time: "20:45", city: "Monza", social_context: "friends" },
  { amount: 1.2, description: "Caffè al lavoro", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-01-19", time: "09:30", city: "Bernareggio", social_context: "colleagues" },
  { amount: 1.2, description: "Bar - Caffè", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-01-20", time: "10:15", city: "Bernareggio" },
  { amount: 1.2, description: "caffè bernareggio lavoro", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-01-21", time: "08:45", city: "Bernareggio", social_context: "colleagues" },
  { amount: 5.51, description: "MD - Spesa pranzo", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-01-22", time: "13:05", city: "Bernareggio" },
  { amount: 10.0, description: "Cinema - Biglietto", category_key: "vita_intrattenimento", subcategory_key: "cultura_eventi", direction: "out", date: "2026-01-24", time: "21:30", city: "Vimercate", social_context: "friends" },
  { amount: 5.0, description: "dolce old Wild West", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-01-25", time: "22:15", city: "Monza", social_context: "friends" },
  { amount: 4.38, description: "MD - Pausa pranzo", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-02-03", time: "13:10", city: "Bernareggio" },
  { amount: 1.2, description: "Caffè Bernareggio - Caffè", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-02-03", time: "13:45", city: "Bernareggio", social_context: "colleagues" },
  { amount: 1.2, description: "Caffè lavoro", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-02-05", time: "10:00", city: "Bernareggio", social_context: "colleagues" },
  { amount: 2.0, description: "Dolcetto pausa lavoro", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-02-06", time: "16:00", city: "Bernareggio", social_context: "colleagues" },
  { amount: 3.5, description: "Schiuma da barba", category_key: "vita_intrattenimento", subcategory_key: "wellness_bellezza", direction: "out", date: "2026-02-07", time: "10:30", city: "Vimercate" },
  { amount: 2.0, description: "Parrucchiere", category_key: "vita_intrattenimento", subcategory_key: "wellness_bellezza", direction: "out", date: "2026-02-07", time: "11:00", city: "Vimercate" },
  { amount: 25.0, description: "Ristorante Goos", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-02-07", time: "20:00", city: "Monza", social_context: "friends" },
  { amount: -2.61, description: "Spesa MD", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "in", date: "2026-02-09", time: "13:20", city: "Bernareggio" },
  { amount: 4.4, description: "Biglietti treno", category_key: "trasporti", subcategory_key: "trasporto_pubblico", direction: "out", date: "2026-02-10", time: "08:15", city: "Milano" },
  { amount: 500.0, description: "Naxa lavoro - Stipendio", category_key: "entrata", subcategory_key: "salario_fatture", direction: "in", date: "2026-02-11", time: "09:00" },
  { amount: 4.4, description: "Treno lavoro", category_key: "trasporti", subcategory_key: "trasporto_pubblico", direction: "out", date: "2026-02-12", time: "08:15", city: "Milano" },
  { amount: 4.28, description: "MD - Spesa pausa lavoro", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-02-13", time: "13:05", city: "Bernareggio", social_context: "colleagues" },
  { amount: 2.2, description: "Biglietti metro", category_key: "trasporti", subcategory_key: "trasporto_pubblico", direction: "out", date: "2026-02-14", time: "11:30", city: "Milano" },
  { amount: 12.0, description: "Pausa pranzo", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-02-14", time: "13:30", city: "Milano", social_context: "friends" },
  { amount: 5.9, description: "Birreria Italiana - Tiramisù", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-02-16", time: "16:45", city: "Monza", social_context: "colleagues" },
  { amount: 3.4, description: "Biglietti del treno", category_key: "trasporti", subcategory_key: "trasporto_pubblico", direction: "out", date: "2026-02-17", time: "08:20", city: "Sesto San Giovanni" },
  { amount: 55.0, description: "Gara kart", category_key: "vita_intrattenimento", subcategory_key: "hobby", direction: "out", date: "2026-02-21", time: "15:00", city: "Cinisello", social_context: "friends" },
  { amount: 1.2, description: "Caffè", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-02-21", time: "16:30", city: "Cinisello", social_context: "friends" },
  { amount: 3.0, description: "Gelato", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-02-21", time: "17:00", city: "Cinisello", social_context: "friends" },
  { amount: 1.65, description: "Coca Cola", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-02-21", time: "17:15", city: "Cinisello", social_context: "friends" },
  { amount: 3.0, description: "Gelato", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-02-21", time: "18:00", city: "Cinisello", social_context: "friends" },
  { amount: 0.86, description: "Groq AI per Obby", category_key: "comunicazione_pc", subcategory_key: "software_app_giochi", direction: "out", date: "2026-02-24", time: "23:00", location_type: "online" },
  { amount: 5.0, description: "MD - Pausa pranzo", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-02-27", time: "13:20", city: "Bernareggio", social_context: "colleagues" },
  { amount: 30.0, description: "Spesa weekend a Schilpario", category_key: "vita_intrattenimento", subcategory_key: "vacanze_viaggi_hotel", direction: "out", date: "2026-02-28", time: "12:00", city: "Schilpario", is_travel: true, social_context: "friends" },
  { amount: 11.0, description: "Kebab", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-02-28", time: "20:00", city: "Schilpario", is_travel: true, social_context: "friends" },
  { amount: 3.2, description: "Latteria Weekend - Yogurt", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-02-28", time: "09:30", city: "Schilpario", is_travel: true, social_context: "friends" },
  { amount: 25.0, description: "Noleggio scii e ingresso pista sci di fondo", category_key: "vita_intrattenimento", subcategory_key: "sport_fitness", direction: "out", date: "2026-03-01", time: "10:00", city: "Schilpario", is_travel: true, social_context: "friends" },
  { amount: 1.12, description: "GROQ INC - Pagamento con carta virtuale", category_key: "vita_intrattenimento", subcategory_key: "hobby", direction: "out", date: "2026-03-06", time: "23:15", location_type: "online" },
  { amount: 21.99, description: "Abbonamento Google One Obby", category_key: "vita_intrattenimento", subcategory_key: "hobby", direction: "out", date: "2026-03-06", time: "10:30", location_type: "online" },
  { amount: 13.73, description: "Pagamento su SPLICE.COM", category_key: "vita_intrattenimento", subcategory_key: "hobby", direction: "out", date: "2026-03-08", time: "11:00", location_type: "online" },
  { amount: 500.0, description: "Accredito stipendio/pensione", category_key: "entrata", subcategory_key: "salario_fatture", direction: "in", date: "2026-03-10", time: "09:00" },
  { amount: 2.85, description: "MD BERNAR, acquisto", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-03-10", time: "13:20", city: "Bernareggio" },
  { amount: 12.8, description: "Acquisto presso MCDONALD'", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-03-13", time: "13:15", city: "Arcore", social_context: "colleagues" },
  { amount: 15.0, description: "Regalo laurea Stefano", category_key: "vita_intrattenimento", subcategory_key: "cultura_eventi", direction: "out", date: "2026-03-14", time: "18:00", social_context: "friends" },
  { amount: 12.0, description: "Mc Donald", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-03-14", time: "13:00", city: "Arcore", social_context: "friends" },
  { amount: 19.0, description: "Ristorante", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-03-14", time: "20:30", city: "Missaglia", social_context: "friends" },
  { amount: 500.0, description: "Regalo papà", category_key: "entrata", subcategory_key: "regali", direction: "in", date: "2026-03-16", time: "10:00", social_context: "family" },
  { amount: 4.55, description: "Spesa MD per pranzo di lavoro", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-03-17", time: "13:10", city: "Bernareggio", social_context: "colleagues" },
  { amount: 1.2, description: "Caffè bar, pausa pranzo", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-03-18", time: "13:45", city: "Bernareggio", social_context: "colleagues" },
  { amount: 6.2, description: "Spesa a Bernareggio durante pausa lavoro", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-03-20", time: "13:30", city: "Bernareggio", social_context: "colleagues" },
  { amount: 8.8, description: "Biglietto treno FNM", category_key: "trasporti", subcategory_key: "trasporto_pubblico", direction: "out", date: "2026-03-23", time: "08:20", city: "Sesto San Giovanni" },
  { amount: 6.2, description: "MD BERNAR, acquisto", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-03-26", time: "13:05", city: "Bernareggio" },
  { amount: 31.67, description: "THAT'S AM, acquisto", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-03-25", time: "20:30", city: "Arcore", social_context: "friends" },
  { amount: 36.1, description: "Acquisto presso ZARA", category_key: "acquisti", subcategory_key: "abbigliamento_scarpe", direction: "out", date: "2026-03-21", time: "17:00", city: "Arese", social_context: "friends" },
  { amount: 1.3, description: "Caffè - Acquisto", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-03-26", time: "09:00", city: "Bernareggio", social_context: "colleagues" },
  { amount: 5.3, description: "Acquisto presso MCDONALD'", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-03-28", time: "13:20", city: "Monza", social_context: "friends" },
  { amount: 110.0, description: "Concerto Bruno Mars", category_key: "vita_intrattenimento", subcategory_key: "cultura_eventi", direction: "out", date: "2026-01-14", time: "21:00", city: "Milano", social_context: "friends" },
  { amount: 11.0, description: "Piadina", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-04-01", time: "13:30", city: "Monza", social_context: "friends" },
  { amount: 1.3, description: "Acquisto presso Eser. MIAMI", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-04-01", time: "10:15", city: "Bernareggio", social_context: "colleagues" },
  { amount: 3.11, description: "Rimborso spese da Mamma, regalo", category_key: "entrata", subcategory_key: "regali", direction: "in", date: "2026-04-04", time: "10:00", social_context: "family" },
  { amount: 0.71, description: "Pagamento con carta virtuale da GROQ INC", category_key: "vita_intrattenimento", subcategory_key: "hobby", direction: "out", date: "2026-04-04", time: "23:05", location_type: "online" },
  { amount: 21.99, description: "Acquisto su GOOGLE", category_key: "vita_intrattenimento", subcategory_key: "hobby", direction: "out", date: "2026-04-04", time: "09:30", location_type: "online" },
  { amount: 6.85, description: "spese MD per pranzo lavoro", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-04-09", time: "13:20", city: "Bernareggio", social_context: "colleagues" },
  { amount: 500.0, description: "Stipendio/pensione accreditato", category_key: "entrata", subcategory_key: "salario_fatture", direction: "in", date: "2026-04-10", time: "09:00" },
  { amount: 2.5, description: "Coca cola", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-04-10", time: "16:00", city: "Monza", social_context: "friends" },
  { amount: 2.8, description: "Gelato", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-04-11", time: "17:30", city: "Arcore", social_context: "friends" },
  { amount: 2.19, description: "MD BERNAReggio lavoro", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-04-13", time: "13:05", city: "Bernareggio" },
  { amount: 6.91, description: "Spesa MD lavoro", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-04-17", time: "13:15", city: "Bernareggio", social_context: "colleagues" },
  { amount: 6.54, description: "Spese MD per pausa lavoro", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-04-23", time: "13:10", city: "Bernareggio", social_context: "colleagues" },
  { amount: 2.2, description: "Biglietto metro", category_key: "trasporti", subcategory_key: "trasporto_pubblico", direction: "out", date: "2026-04-26", time: "11:00", city: "Milano" },
  { amount: 5.0, description: "Cinema", category_key: "vita_intrattenimento", subcategory_key: "cultura_eventi", direction: "out", date: "2026-04-24", time: "21:30", city: "Vimercate", social_context: "friends" },
  { amount: 5.0, description: "Biliardo", category_key: "vita_intrattenimento", subcategory_key: "hobby", direction: "in", date: "2026-04-04", time: "18:00", city: "Merate", social_context: "friends" },
  { amount: 16.29, description: "Acquisto presso HM", category_key: "acquisti", subcategory_key: "abbigliamento_scarpe", direction: "out", date: "2026-04-26", time: "16:00", city: "Milano" },
  { amount: 9.99, description: "CC PULL&B", category_key: "acquisti", subcategory_key: "abbigliamento_scarpe", direction: "out", date: "2026-04-26", time: "17:00", city: "Milano", social_context: "friends" },
  { amount: 5.75, description: "Spesa Esselunga e fiori mamma", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-04-26", time: "19:00", city: "Monza", social_context: "family" },
  { amount: 1.99, description: "Spesa MD per pausa lavoro", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-04-27", time: "13:05", city: "Bernareggio", social_context: "colleagues" },
  { amount: 46.19, description: "Benzina", category_key: "veicolo", subcategory_key: "carburante", direction: "out", date: "2026-04-29", time: "08:00", city: "Vimercate" },
  { amount: 5.09, description: "Spesa lavoro", category_key: "cibo_bevande", subcategory_key: "alimentari", direction: "out", date: "2026-04-30", time: "13:10", city: "Bernareggio", social_context: "colleagues" },
  { amount: 12.75, description: "Treno per Torino", category_key: "trasporti", subcategory_key: "trasporto_pubblico", direction: "out", date: "2026-05-01", time: "09:00", city: "Torino", is_travel: true, social_context: "friends" },
  { amount: 15.0, description: "Museo dell'automobile", category_key: "vita_intrattenimento", subcategory_key: "cultura_eventi", direction: "out", date: "2026-05-01", time: "11:00", city: "Torino", is_travel: true, social_context: "friends" },
  { amount: 23.0, description: "Pagamento elettronico presso VIA IPPIZZIUM S.P.A.", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-05-01", time: "13:30", city: "Torino", is_travel: true, social_context: "friends" },
  { amount: 4.0, description: "Gelato", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-05-01", time: "16:00", city: "Torino", is_travel: true, social_context: "friends" },
  { amount: 9.0, description: "Pagamento con carta presso LENRY", category_key: "cibo_bevande", subcategory_key: "bar_caffe", direction: "out", date: "2026-05-01", time: "19:00", city: "Monza", social_context: "friends" },
  { amount: 11.65, description: "KFC MB MO", category_key: "cibo_bevande", subcategory_key: "ristorante_fast_food", direction: "out", date: "2026-05-01", time: "20:30", city: "Monza", social_context: "friends" },
  { amount: 12.75, description: "biglietto ritorno", category_key: "trasporti", subcategory_key: "trasporto_pubblico", direction: "out", date: "2026-05-01", time: "22:00", city: "Monza", is_travel: true, social_context: "friends" },
];

export const prepareDummyForInsert = (dummy: Partial<ParsedExpense>): ParsedExpense => {
  const now = new Date();
  const dateStr = dummy.date || now.toISOString().split('T')[0];
  const d = new Date(dateStr);
  const days = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];
  const dayOfWeek = days[d.getDay()];
  const isWeekend = d.getDay() === 0 || d.getDay() === 6;

  const socialMap: Record<string, string> = {
    amici: 'friends',
    famiglia: 'family',
    colleghi: 'colleagues',
    coppia: 'couple',
    solo: 'alone',
    sconosciuti: 'strangers',
  };

  const locationTypeMap: Record<string, string> = {
    negozio_fisico: 'physical_store',
    lavoro: 'work',
    ristorante: 'restaurant',
    casa: 'home',
    trasporti: 'transport',
    viaggio: 'travel',
    estero: 'abroad',
    online: 'online',
  };

  const rawSocial = dummy.social_context ? dummy.social_context.toLowerCase() : null;
  const mappedSocial = rawSocial ? (socialMap[rawSocial] || rawSocial) : 'alone';

  const rawLocation = dummy.location_type ? dummy.location_type.toLowerCase() : null;
  const mappedLocation = rawLocation ? (locationTypeMap[rawLocation] || rawLocation) : 'physical_store';

  return {
    id: uuid.v4() as string,
    created_at: now.toISOString(),
    amount: dummy.amount || 0,
    net_amount: dummy.amount || 0,
    currency: 'EUR',
    payment_method: dummy.payment_method || 'Carta',
    direction: (dummy.direction as 'in' | 'out') || 'out',
    category_key: dummy.category_key || 'varie',
    subcategory_key: dummy.subcategory_key || dummy.category_key || 'varie',
    category_confidence: 1.0,
    date: dateStr,
    time: dummy.time || "12:00",
    time_of_day: (dummy.time ? (parseInt(dummy.time.split(':')[0]) < 13 ? 'morning' : 'afternoon') : 'afternoon') as any,
    is_weekend: isWeekend,
    day_of_week: dayOfWeek,
    social_context: mappedSocial as SocialContext,
    people_mentioned: dummy.people_mentioned || [],
    group_size: dummy.group_size || (dummy.people_mentioned ? dummy.people_mentioned.length + 1 : 1),
    is_social: !!dummy.social_context && mappedSocial !== 'alone',
    location_type: mappedLocation as LocationType,
    location_name: dummy.location_name || null,
    city: dummy.city || 'Milano',
    address: dummy.address || null,
    is_travel: dummy.is_travel || false,
    is_online: dummy.location_type === 'online',
    is_recurring_pattern: dummy.is_recurring_pattern || false,
    refund: null,
    split: null,
    reason: null,
    description: dummy.description || 'Dato fittizio',
    input_method: 'manual',
    raw_input: 'Dato di test simulato',
    holiday: null,
    tags: [],
    is_deleted: false,
    synced_at: null
  };
};
