import { getDBConnection } from '../db';
import uuid from 'react-native-uuid';

export type Frequency = 'monthly' | 'weekly' | 'biweekly' | 'yearly';

export interface Subscription {
  id?: string;
  created_at?: string;
  name: string;
  amount: number;
  currency?: string;
  direction?: 'in' | 'out';
  category_key: string;
  frequency: Frequency;
  recurrence_day?: number | null; // day-of-month (1-31) or day-of-week (0=Mon…6=Sun)
  start_date: string;              // YYYY-MM-DD
  end_date?: string | null;        // null = still active
  auto_detected?: boolean;
  is_active?: boolean;
}

export class SubscriptionRepository {
  // ─── Write ────────────────────────────────────────────────────────────────

  static async insert(sub: Subscription): Promise<string> {
    const db = await getDBConnection();
    const id = sub.id || uuid.v4().toString();
    const now = new Date().toISOString();

    await db.runAsync(
      `INSERT INTO subscriptions (
        id, created_at, name, amount, currency, direction, category_key,
        frequency, recurrence_day, start_date, end_date, auto_detected, is_active, synced_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        id,
        now,
        sub.name,
        sub.amount,
        sub.currency || 'EUR',
        sub.direction || 'out',
        sub.category_key,
        sub.frequency,
        sub.recurrence_day ?? null,
        sub.start_date,
        sub.end_date ?? null,
        sub.auto_detected ? 1 : 0,
        sub.is_active !== false ? 1 : 0,
        null,
      ]
    );

    return id;
  }

  static async update(id: string, fields: Partial<Subscription>): Promise<void> {
    const db = await getDBConnection();
    const updates: string[] = [];
    const values: any[] = [];

    if (fields.name !== undefined)              { updates.push('name = ?');              values.push(fields.name); }
    if (fields.amount !== undefined)            { updates.push('amount = ?');            values.push(fields.amount); }
    if (fields.direction !== undefined)         { updates.push('direction = ?');         values.push(fields.direction); }
    if (fields.category_key !== undefined)     { updates.push('category_key = ?');     values.push(fields.category_key); }
    if (fields.frequency !== undefined)         { updates.push('frequency = ?');         values.push(fields.frequency); }
    if (fields.recurrence_day !== undefined) { updates.push('recurrence_day = ?'); values.push(fields.recurrence_day); }
    if (fields.start_date !== undefined)       { updates.push('start_date = ?');       values.push(fields.start_date); }
    if (fields.end_date !== undefined)         { updates.push('end_date = ?');         values.push(fields.end_date); }
    if (fields.is_active !== undefined)            { updates.push('is_active = ?');            values.push(fields.is_active ? 1 : 0); }

    if (updates.length === 0) return;
    values.push(id);

    await db.runAsync(
      `UPDATE subscriptions SET ${updates.join(', ')} WHERE id = ?`,
      values
    );
  }

  static async setIsActive(id: string, is_active: boolean): Promise<void> {
    const db = await getDBConnection();
    await db.runAsync(`UPDATE subscriptions SET is_active = ? WHERE id = ?`, [is_active ? 1 : 0, id]);
  }

  static async delete(id: string): Promise<void> {
    const db = await getDBConnection();
    await db.runAsync(`DELETE FROM subscriptions WHERE id = ?`, [id]);
  }

  // ─── Read ─────────────────────────────────────────────────────────────────

  static async getAll(): Promise<Subscription[]> {
    const db = await getDBConnection();
    const rows = await db.getAllAsync(`SELECT * FROM subscriptions ORDER BY created_at DESC`);
    return rows.map(mapRow);
  }

  static async getActive(): Promise<Subscription[]> {
    const db = await getDBConnection();
    const today = new Date().toISOString().split('T')[0];
    const rows = await db.getAllAsync(
      `SELECT * FROM subscriptions
       WHERE is_active = 1 AND (end_date IS NULL OR end_date >= ?)
       ORDER BY name ASC`,
      [today]
    );
    return rows.map(mapRow);
  }

  static async getById(id: string): Promise<Subscription | null> {
    const db = await getDBConnection();
    const row = await db.getFirstAsync(`SELECT * FROM subscriptions WHERE id = ?`, [id]);
    return row ? mapRow(row) : null;
  }

  /**
   * Idempotency check: returns true if a transaction for this subscription
   * already exists on the given cycle date.
   */
  static async hasTransactionForCycle(subscription_id: string, cycleDate: string): Promise<boolean> {
    const db = await getDBConnection();
    const row = await db.getFirstAsync(
      `SELECT id FROM transactions
       WHERE subscription_id = ? AND date = ? AND is_deleted = 0
       LIMIT 1`,
      [subscription_id, cycleDate]
    );
    return !!row;
  }

  /**
   * Returns all transactions generated by a given subscription (for history view).
   */
  static async getTransactionsFor(subscription_id: string): Promise<any[]> {
    const db = await getDBConnection();
    return db.getAllAsync(
      `SELECT * FROM transactions
       WHERE subscription_id = ? AND is_deleted = 0
       ORDER BY date DESC`,
      [subscription_id]
    );
  }

  /**
   * Total monthly cost across all active subscriptions (normalized to monthly).
   */
  static async getTotalMonthly(): Promise<number> {
    const active = await this.getActive();
    return active.filter(s => (s.direction || 'out') === 'out').reduce((sum, sub) => {
      let monthly = sub.amount;
      switch (sub.frequency) {
        case 'weekly':    monthly = sub.amount * 4.33; break;
        case 'biweekly':  monthly = sub.amount * 2.17; break;
        case 'yearly':        monthly = sub.amount / 12;   break;
        default:               monthly = sub.amount;        break; // monthly
      }
      return sum + monthly;
    }, 0);
  }

  /**
   * Total monthly income across all active periodic incomes (normalized to monthly).
   */
  static async getTotalMonthlyIncome(): Promise<number> {
    const active = await this.getActive();
    return active.filter(s => s.direction === 'in').reduce((sum, sub) => {
      let monthly = sub.amount;
      switch (sub.frequency) {
        case 'weekly':    monthly = sub.amount * 4.33; break;
        case 'biweekly':  monthly = sub.amount * 2.17; break;
        case 'yearly':        monthly = sub.amount / 12;   break;
        default:               monthly = sub.amount;        break;
      }
      return sum + monthly;
    }, 0);
  }
}

function mapRow(row: any): Subscription {
  return {
    id: row.id,
    created_at: row.created_at,
    name: row.name,
    amount: row.amount,
    currency: row.currency,
    direction: row.direction,
    category_key: row.category_key,
    frequency: row.frequency as Frequency,
    recurrence_day: row.recurrence_day,
    start_date: row.start_date,
    end_date: row.end_date ?? null,
    auto_detected: row.auto_detected === 1,
    is_active: row.is_active === 1,
  };
}
