import { RecurringPaymentRepository } from './repositories/RecurringPaymentRepository';
import { TransactionRepository } from './repositories/TransactionRepository';
import { ParsedExpense } from '../../modules/registration/types';
import uuid from 'react-native-uuid';

export class SubscriptionManager {
  static async processDueSubscriptions() {
    try {
      const now = new Date();
      // Format as YYYY-MM-DD
      const todayIso = now.toISOString().split('T')[0]; 
      
      const duePayments = await RecurringPaymentRepository.getDuePayments(todayIso);
      
      for (const payment of duePayments) {
        // Create a new transaction from the recurring payment
        const newTransaction: ParsedExpense = {
          id: uuid.v4().toString(),
          created_at: new Date().toISOString(),
          amount: payment.amount,
          net_amount: payment.amount,
          currency: payment.currency,
          payment_method: payment.payment_method || null,
          direction: payment.direction,
          category_key: payment.category_key,
          subcategory_key: payment.subcategory_key,
          category_confidence: 1,
          date: payment.next_due_date,
          time: null,
          time_of_day: null,
          is_weekend: false,
          day_of_week: '', // Optional, can calculate
          social_context: null,
          people_mentioned: [],
          group_size: null,
          is_social: false,
          location_type: null,
          location_name: null,
          city: null,
          address: null,
          is_travel: false,
          is_online: true,
          is_recurring_pattern: true,
          reason: null,
          description: payment.description,
          refund: null,
          split: null,
          input_method: 'manual', // conceptually this is auto, but fits our types
          raw_input: 'Generated by SubscriptionManager',
          is_deleted: false,
          synced_at: null
        };

        await TransactionRepository.insert(newTransaction);

        // Calculate next due date
        const currentDueDate = new Date(payment.next_due_date);
        if (payment.frequency === 'monthly') {
          currentDueDate.setMonth(currentDueDate.getMonth() + 1);
        } else if (payment.frequency === 'yearly') {
          currentDueDate.setFullYear(currentDueDate.getFullYear() + 1);
        } else if (payment.frequency === 'weekly') {
          currentDueDate.setDate(currentDueDate.getDate() + 7);
        }
        
        const nextDueStr = currentDueDate.toISOString().split('T')[0];
        await RecurringPaymentRepository.updateNextDueDate(payment.id, nextDueStr);
      }
    } catch (error) {
      console.error('Error processing subscriptions:', error);
    }
  }
}
