import { SubscriptionRepository, Subscription, Frequency } from './repositories/SubscriptionRepository';
import { TransactionRepository } from './repositories/TransactionRepository';
import { ParsedExpense } from '../../modules/registration/types';
import uuid from 'react-native-uuid';

// ─── Date Helpers ────────────────────────────────────────────────────────────

/**
 * Given a subscription, returns the cycle date (YYYY-MM-DD) that would fall
 * on or within the current cycle relative to `today`.
 * Returns null if today is not the cycle day.
 */
function getCycleDateForToday(sub: Subscription, today: Date): string | null {
  const todayISO = today.toISOString().split('T')[0];
  const todayDay = today.getDate();
  const todayDow = (today.getDay() + 6) % 7; // 0=Mon…6=Sun
  const startDate = new Date(sub.start_date);
  const recurrenceDay = sub.recurrence_day;

  switch (sub.frequency) {
    case 'monthly': {
      // Fire on the specified day-of-month each month
      if (recurrenceDay != null && todayDay === recurrenceDay) {
        return todayISO;
      }
      return null;
    }

    case 'yearly': {
      // Fire on the same day+month as startDate
      const startMonth = startDate.getMonth(); // 0-based
      const startDay = startDate.getDate();
      if (today.getMonth() === startMonth && todayDay === startDay) {
        return todayISO;
      }
      return null;
    }

    case 'weekly': {
      // Fire on the specified day-of-week (0=Mon…6=Sun)
      if (recurrenceDay != null && todayDow === recurrenceDay) {
        return todayISO;
      }
      return null;
    }

    case 'biweekly': {
      // Fire every 14 days from startDate, on the correct day-of-week
      if (recurrenceDay != null && todayDow !== recurrenceDay) return null;
      const msPerDay = 86400000;
      const daysSinceStart = Math.floor((today.getTime() - startDate.getTime()) / msPerDay);
      if (daysSinceStart >= 0 && daysSinceStart % 14 === 0) {
        return todayISO;
      }
      return null;
    }

    default:
      return null;
  }
}

// ─── Main Job ────────────────────────────────────────────────────────────────

/**
 * Called on every app open (from app/index.tsx).
 * Idempotent: safe to call multiple times per day.
 */
export class SubscriptionManager {
  static async processDueSubscriptions(): Promise<void> {
    try {
      const today = new Date();
      const active = await SubscriptionRepository.getActive();

      for (const sub of active) {
        const cycleDate = getCycleDateForToday(sub, today);
        if (!cycleDate) continue; // not due today

        const alreadyExists = await SubscriptionRepository.hasTransactionForCycle(sub.id!, cycleDate);
        if (alreadyExists) continue; // idempotency guard

        // Create the transaction
        const newTx: ParsedExpense = {
          id: uuid.v4().toString(),
          created_at: new Date().toISOString(),
          amount: sub.amount,
          net_amount: sub.amount,
          currency: sub.currency || 'EUR',
          payment_method: null,
          direction: (sub.direction || 'out') as 'in' | 'out',
          category_key: sub.category_key,
          subcategory_key: sub.category_key,
          category_confidence: 1,
          date: cycleDate,
          time: null,
          time_of_day: null,
          is_weekend: false,
          day_of_week: '',
          social_context: null,
          people_mentioned: [],
          group_size: null,
          is_social: false,
          location_type: null,
          location_name: null,
          city: null,
          address: null,
          is_travel: false,
          is_online: true,
          is_recurring_pattern: true,
          reason: null,
          description: sub.name,
          refund: null,
          split: null,
          input_method: 'manual',
          raw_input: `Auto-generated by SubscriptionManager: ${sub.name}`,
          is_deleted: false,
          synced_at: null,
        };

        await TransactionRepository.insert(newTx, sub.id);

        console.log(`[SubscriptionManager] Created transaction for "${sub.name}" on ${cycleDate}`);
      }
    } catch (error) {
      console.error('[SubscriptionManager] Error processing subscriptions:', error);
    }
  }
}
